Repository dnb-asa/figma, pull requests merged in 2020-09, with the labels that each got.

#7 Migrate to HTTP2
  lib/src/client.dart
  lib/src/converters/converters.dart
  lib/src/converters/node.dart
  lib/src/models/boolean_operation.dart
  lib/src/models/boolean_operation.g.dart
  lib/src/models/canvas.dart
  lib/src/models/canvas.g.dart
  lib/src/models/document.dart
  lib/src/models/document.g.dart
  lib/src/models/ellipse.dart
  lib/src/models/ellipse.g.dart
  lib/src/models/frame.dart
  lib/src/models/frame.g.dart
  lib/src/models/group.dart
  lib/src/models/group.g.dart
  lib/src/models/instance.dart
  lib/src/models/instance.g.dart
  lib/src/models/line.dart
  lib/src/models/line.g.dart
  lib/src/models/rectangle.dart
  lib/src/models/rectangle.g.dart
  lib/src/models/regular_polygon.dart
  lib/src/models/regular_polygon.g.dart
  lib/src/models/slice.dart
  lib/src/models/slice.g.dart
  lib/src/models/star.dart
  lib/src/models/star.g.dart
  lib/src/models/style_type.dart
  lib/src/models/text.dart
  lib/src/models/text.g.dart
  lib/src/models/vector.dart
  lib/src/models/vector.g.dart
  pubspec.yaml
Labels: bug

#9 Add devcontainer config
  .devcontainer/devcontainer.json
Labels: enhancement

#10 Fix nits, docs and formatting to satsify the Pub analysis
  CHANGELOG.md
  README.md
  lib/figma.dart
  lib/src/client.dart
  lib/src/converters/node.dart
  lib/src/models/layout_constraint.dart
  lib/src/query.dart
  pubspec.yaml
Labels: documentation

#11 Fixed 'layoutConstraints' property by renaming it to 'constraints'.
  lib/src/models/boolean_operation.dart
  lib/src/models/boolean_operation.g.dart
  lib/src/models/ellipse.dart
  lib/src/models/ellipse.g.dart
  lib/src/models/line.dart
  lib/src/models/line.g.dart
  lib/src/models/rectangle.dart
  lib/src/models/rectangle.g.dart
  lib/src/models/regular_polygon.dart
  lib/src/models/regular_polygon.g.dart
  lib/src/models/star.dart
  lib/src/models/star.g.dart
  lib/src/models/text.dart
  lib/src/models/text.g.dart
  lib/src/models/vector.dart
  lib/src/models/vector.g.dart
Labels: bug
